### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [swrj/ThreadingMapReduce#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by swrj** [comment]
It's an old college assignment, didn't think to put a license, feel free to clone or use it however you'd like.

**Comment by suprafun** [comment]
Thank you so very much. Would it be possible for you to upload a formal license (e.g. MIT, BSD, GPL, whatever) to the repo. ? Sorry for asking, I just want to be sure of what I should do : ). Thank you again.

**Comment by swrj** [comment]
np, done
